'use client'
import {createContext,useContext,useEffect,useState} from 'react'
import Link from 'next/link'
import {products} from '@/data/catalog'
import {gifts} from '@/data/gifts'
type Store={cart:Record<string,number>;wishlist:string[];drawer:boolean;setDrawer:(v:boolean)=>void;add:(id:string,openDrawer?:boolean)=>void;qty:(id:string,n:number)=>void;toggleWish:(id:string)=>void}
const C=createContext<Store|null>(null)
export function StoreProvider({children}:{children:React.ReactNode}){const[cart,setCart]=useState<Record<string,number>>({});const[wishlist,setWishlist]=useState<string[]>([]);const[drawer,setDrawer]=useState(false);const[ready,setReady]=useState(false);useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('angdi-cart')||'{}'));setWishlist(JSON.parse(localStorage.getItem('angdi-wishlist')||'[]'))}finally{setReady(true)}},[]);useEffect(()=>{if(ready)localStorage.setItem('angdi-cart',JSON.stringify(cart))},[cart,ready]);useEffect(()=>{if(ready)localStorage.setItem('angdi-wishlist',JSON.stringify(wishlist))},[wishlist,ready]);const add=(id:string,openDrawer=true)=>{setCart(c=>({...c,[id]:(c[id]||0)+1}));if(openDrawer)setDrawer(true)};const qty=(id:string,n:number)=>setCart(c=>{const x={...c};if(n<=0)delete x[id];else x[id]=n;return x});const toggleWish=(id:string)=>setWishlist(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);return <C.Provider value={{cart,wishlist,drawer,setDrawer,add,qty,toggleWish}}>{children}</C.Provider>}
export const useStore=()=>{const c=useContext(C);if(!c)throw Error('store');return c}
export function CartDrawer(){const{cart,drawer,setDrawer,qty}=useStore();const items=[...products,...gifts].filter(p=>cart[p.id]);const total=items.reduce((s,p)=>s+p.price*cart[p.id],0);return <><button className={'scrim '+(drawer?'show':'')} onClick={()=>setDrawer(false)} aria-label="Close cart"/><aside className={'drawer '+(drawer?'open':'')} role="dialog" aria-modal="true" aria-label="Shopping bag"><div className="drawer-head"><h2>Your bag</h2><button className="icon" onClick={()=>setDrawer(false)} aria-label="Close cart">×</button></div>{!items.length?<div className="empty"><span>◎</span><h3>Your cart is waiting</h3><p>Take a trip through Karnataka and add a favourite.</p><Link className="button" href="/shop" onClick={()=>setDrawer(false)}>Browse snacks</Link></div>:<><div className="cart-lines">{items.map(p=><div className="cart-line" key={p.id}><Link className="cart-line-image" href={'/products/'+p.slug} onClick={()=>setDrawer(false)} aria-label={`View ${p.name}`}><img src={p.image} alt=""/></Link><div><Link className="cart-line-title" href={'/products/'+p.slug} onClick={()=>setDrawer(false)}><b>{p.name}</b><small>{p.region}</small></Link><div className="stepper"><button onClick={()=>qty(p.id,cart[p.id]-1)}>−</button><span>{cart[p.id]}</span><button onClick={()=>qty(p.id,cart[p.id]+1)}>+</button></div></div><strong>₹{p.price*cart[p.id]}</strong><button className="cart-remove" onClick={()=>qty(p.id,0)} aria-label={`Remove ${p.name} from cart`} title="Remove from cart"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5"/></svg></button></div>)}</div><div className="subtotal"><span>Subtotal</span><b>₹{total}</b></div><Link className="button wide" href="/checkout">Continue to checkout</Link><small>Shipping is calculated at checkout.</small></>}</aside></>}
