'use client'
import {useMemo,useState} from 'react'
import {products,regions} from '@/data/catalog'
import {ProductCard} from '@/components/Commerce'
const PAGE=8
export default function Shop(){
 const[q,setQ]=useState('');const[cat,setCat]=useState('All');const[region,setRegion]=useState('All');const[heat,setHeat]=useState('All');const[sort,setSort]=useState('featured');const[page,setPage]=useState(1);const[filtersOpen,setFiltersOpen]=useState(true)
 const list=useMemo(()=>products.filter(p=>(!q||[p.name,p.region,p.category].join(' ').toLowerCase().includes(q.toLowerCase()))&&(cat==='All'||p.category===cat)&&(region==='All'||p.region===region)&&(heat==='All'||p.heat===heat)).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:a.name.localeCompare(b.name)),[q,cat,region,heat,sort]);const pages=Math.max(1,Math.ceil(list.length/PAGE));const change=(fn:(x:string)=>void,v:string)=>{fn(v);setPage(1)};const clear=()=>{setQ('');setCat('All');setRegion('All');setHeat('All');setPage(1)}
 return <div className="shop-page"><header className="shop-hero"><span className="eyebrow">FROM EVERY CORNER OF KARNATAKA</span><h1>Find your thindi.</h1><p>Explore a working catalogue designed around place, taste and the rituals snacks belong to.</p><div className="shop-search"><span>⌕</span><input value={q} onChange={e=>change(setQ,e.target.value)} placeholder="Search products, regions or categories" aria-label="Search products"/></div></header><div className="shop-view-controls"><button className="filter-toggle" onClick={()=>setFiltersOpen(v=>!v)} aria-expanded={filtersOpen} aria-controls="shop-filters"><span aria-hidden="true">☷</span>{filtersOpen?'Hide filters':'Show filters'}</button></div><div className={'shop-layout '+(!filtersOpen?'filters-collapsed':'')}><aside id="shop-filters" className={'filters '+(!filtersOpen?'closed':'')}><details open><summary>Category <span>⌄</span></summary><div className="filter-options">{['All','Savoury','Mixture','Sweet','Bakery'].map(x=><button className={cat===x?'active':''} key={x} onClick={()=>change(setCat,x)}>{x}</button>)}</div></details><details open><summary>Region <span>⌄</span></summary><div className="filter-options"><select aria-label="Filter by region" value={region} onChange={e=>change(setRegion,e.target.value)}><option>All</option>{regions.map(r=><option key={r.slug}>{r.name}</option>)}<option>Bengaluru</option></select></div></details><details open><summary>Spice <span>⌄</span></summary><div className="filter-options">{['All','Mild','Medium','Spicy'].map(x=><button className={heat===x?'active':''} key={x} onClick={()=>change(setHeat,x)}>{x}</button>)}</div></details><button className="clear" onClick={clear}>Clear filters</button></aside><section className="catalogue"><div className="catalogue-head"><span>{list.length} snacks</span><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">A–Z</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>{list.length?<div className="product-grid">{list.slice((page-1)*PAGE,page*PAGE).map(p=><ProductCard key={p.id} p={p}/>)}</div>:<div className="empty"><h3>No snacks on this route.</h3><p>Try clearing one of the filters.</p></div>}<nav className="pagination" aria-label="Product pages"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>←</button>{Array.from({length:pages},(_,i)=><button key={i} className={page===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>→</button></nav></section></div></div>
}
